import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app/app.dart';
import 'firebase_options.dart';

Future<void> main() async {
  // Required before any async work runs ahead of runApp.
  WidgetsFlutterBinding.ensureInitialized();

  // Connect to the Firebase project generated by `flutterfire configure`.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // ProviderScope is the root of Riverpod: it stores the state of every
  // provider and makes `ref` available to the whole widget tree.
  runApp(const ProviderScope(child: AluVenturesApp()));
}
